version: '3'

services: 
  api-solid-pg:
    image: bitnami/postgresql
    ports:
     - 5432:5432
    environments:
     - POSTGRESQL_USERNAME=pedroalberto
     - POSTGRESQL_PASSWORD=pe991007
     - POSTGRESQL_DATABASE=wine-rating